# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
#  - julia -e 'ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
#  - julia -e 'cd(Pkg.dir("Bridge")); include(joinpath("docs", "make.jl"))'
